# Generated by Django 4.2.5 on 2023-09-13 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendor',
            name='vendor_slug',
        ),
    ]
